GET http://localhost:8000/users

### POST USERS
POST http://localhost:8000/users
Content-Type: application/json

{
    "firstName": "Guilherme",
    "lastName": "Moura",
    "email": "guilherme.com",
    "password": "123"
}

### PATCH USER
PATCH http://localhost:8000/users/6793000ac9b2ced766ba1b8a
Content-Type: application/json

{
    "firstName": "Guilherme",
    "lastName": "Silva",
    "password": "123"
}